const classdata = [
  {
    className: "1",
    classTeacher: "Richard Doe",
    totalSeats: "50",
    seatAvailable: "20",
  },
  {
    className: "2",
    classTeacher: "Jane Smith",
    totalSeats: "50",
    seatAvailable: "18",
  },
  {
    className: "3",
    classTeacher: "Michael Johnson",
    totalSeats: "50",
    seatAvailable: "22",
  },
  {
    className: "4",
    classTeacher: "Emily Davis",
    totalSeats: "50",
    seatAvailable: "25",
  },
  {
    className: "5",
    classTeacher: "William Brown",
    totalSeats: "50",
    seatAvailable: "19",
  },
  {
    className: "6",
    classTeacher: "Patricia Wilson",
    totalSeats: "50",
    seatAvailable: "23",
  },
  {
    className: "7",
    classTeacher: "Linda Taylor",
    totalSeats: "50",
    seatAvailable: "21",
  },
  {
    className: "8",
    classTeacher: "Barbara Anderson",
    totalSeats: "50",
    seatAvailable: "20",
  },
  {
    className: "9",
    classTeacher: "James Thomas",
    totalSeats: "50",
    seatAvailable: "17",
  },
  {
    className: "10",
    classTeacher: "Robert Jackson",
    totalSeats: "50",
    seatAvailable: "16",
  },
  {
    className: "11",
    classTeacher: "Mary White",
    totalSeats: "50",
    seatAvailable: "24",
  },
  {
    className: "12",
    classTeacher: "Charles Harris",
    totalSeats: "50",
    seatAvailable: "18",
  },
];

const rejectedStudentList = [
  {
    studentName: "Robert Doe",
    fatherName: "Richard Doe",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Alice Johnson",
    fatherName: "Robert Johnson",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Ben Smith",
    fatherName: "Michael Smith",
    mobile: "9876543211",
    marksScored: "85",
    appliedFor: "Class 2",
    seatsAvailable: "8",
  },
  {
    studentName: "Carol Davis",
    fatherName: "James Davis",
    mobile: "9876543212",
    marksScored: "78",
    appliedFor: "Class 3",
    seatsAvailable: "12",
  },
  {
    studentName: "David Wilson",
    fatherName: "William Wilson",
    mobile: "9876543213",
    marksScored: "82",
    appliedFor: "Class 4",
    seatsAvailable: "15",
  },
  {
    studentName: "Eva Brown",
    fatherName: "Richard Brown",
    mobile: "9876543214",
    marksScored: "90",
    appliedFor: "Class 5",
    seatsAvailable: "9",
  },
  {
    studentName: "Frank Taylor",
    fatherName: "Charles Taylor",
    mobile: "9876543215",
    marksScored: "88",
    appliedFor: "Class 6",
    seatsAvailable: "11",
  },
  {
    studentName: "Grace Thomas",
    fatherName: "Edward Thomas",
    mobile: "9876543216",
    marksScored: "84",
    appliedFor: "Class 7",
    seatsAvailable: "14",
  },
  {
    studentName: "Henry Harris",
    fatherName: "George Harris",
    mobile: "9876543217",
    marksScored: "87",
    appliedFor: "Class 8",
    seatsAvailable: "13",
  },
  {
    studentName: "Isla White",
    fatherName: "Thomas White",
    mobile: "9876543218",
    marksScored: "83",
    appliedFor: "Class 9",
    seatsAvailable: "10",
  },
  {
    studentName: "Jack Lee",
    fatherName: "Henry Lee",
    mobile: "9876543219",
    marksScored: "86",
    appliedFor: "Class 10",
    seatsAvailable: "12",
  },
  {
    studentName: "Kara Martin",
    fatherName: "Paul Martin",
    mobile: "9876543220",
    marksScored: "89",
    appliedFor: "Class 11",
    seatsAvailable: "11",
  },
  {
    studentName: "Liam Jackson",
    fatherName: "Mark Jackson",
    mobile: "9876543221",
    marksScored: "91",
    appliedFor: "Class 12",
    seatsAvailable: "10",
  },
];

const selectedStdList = [
  {
    studentName: "Robert Doe",
    fatherName: "Richard Doe",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Alice Johnson",
    fatherName: "Robert Johnson",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Ben Smith",
    fatherName: "Michael Smith",
    mobile: "9876543211",
    marksScored: "85",
    appliedFor: "Class 2",
    seatsAvailable: "8",
  },
  {
    studentName: "Carol Davis",
    fatherName: "James Davis",
    mobile: "9876543212",
    marksScored: "78",
    appliedFor: "Class 3",
    seatsAvailable: "12",
  },
  {
    studentName: "David Wilson",
    fatherName: "William Wilson",
    mobile: "9876543213",
    marksScored: "82",
    appliedFor: "Class 4",
    seatsAvailable: "15",
  },
  {
    studentName: "Eva Brown",
    fatherName: "Richard Brown",
    mobile: "9876543214",
    marksScored: "90",
    appliedFor: "Class 5",
    seatsAvailable: "9",
  },
  {
    studentName: "Frank Taylor",
    fatherName: "Charles Taylor",
    mobile: "9876543215",
    marksScored: "88",
    appliedFor: "Class 6",
    seatsAvailable: "11",
  },
  {
    studentName: "Grace Thomas",
    fatherName: "Edward Thomas",
    mobile: "9876543216",
    marksScored: "84",
    appliedFor: "Class 7",
    seatsAvailable: "14",
  },
  {
    studentName: "Henry Harris",
    fatherName: "George Harris",
    mobile: "9876543217",
    marksScored: "87",
    appliedFor: "Class 8",
    seatsAvailable: "13",
  },
  {
    studentName: "Isla White",
    fatherName: "Thomas White",
    mobile: "9876543218",
    marksScored: "83",
    appliedFor: "Class 9",
    seatsAvailable: "10",
  },
  {
    studentName: "Jack Lee",
    fatherName: "Henry Lee",
    mobile: "9876543219",
    marksScored: "86",
    appliedFor: "Class 10",
    seatsAvailable: "12",
  },
  {
    studentName: "Kara Martin",
    fatherName: "Paul Martin",
    mobile: "9876543220",
    marksScored: "89",
    appliedFor: "Class 11",
    seatsAvailable: "11",
  },
  {
    studentName: "Liam Jackson",
    fatherName: "Mark Jackson",
    mobile: "9876543221",
    marksScored: "91",
    appliedFor: "Class 12",
    seatsAvailable: "10",
  },
];

const totalStdList = [
  {
    studentName: "Robert Doe",
    fatherName: "Richard Doe",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Alice Johnson",
    fatherName: "Robert Johnson",
    mobile: "9876543210",
    marksScored: "80",
    appliedFor: "Class 1",
    seatsAvailable: "10",
  },
  {
    studentName: "Ben Smith",
    fatherName: "Michael Smith",
    mobile: "9876543211",
    marksScored: "85",
    appliedFor: "Class 2",
    seatsAvailable: "8",
  },
  {
    studentName: "Carol Davis",
    fatherName: "James Davis",
    mobile: "9876543212",
    marksScored: "78",
    appliedFor: "Class 3",
    seatsAvailable: "12",
  },
  {
    studentName: "David Wilson",
    fatherName: "William Wilson",
    mobile: "9876543213",
    marksScored: "82",
    appliedFor: "Class 4",
    seatsAvailable: "15",
  },
  {
    studentName: "Eva Brown",
    fatherName: "Richard Brown",
    mobile: "9876543214",
    marksScored: "90",
    appliedFor: "Class 5",
    seatsAvailable: "9",
  },
  {
    studentName: "Frank Taylor",
    fatherName: "Charles Taylor",
    mobile: "9876543215",
    marksScored: "88",
    appliedFor: "Class 6",
    seatsAvailable: "11",
  },
  {
    studentName: "Grace Thomas",
    fatherName: "Edward Thomas",
    mobile: "9876543216",
    marksScored: "84",
    appliedFor: "Class 7",
    seatsAvailable: "14",
  },
  {
    studentName: "Henry Harris",
    fatherName: "George Harris",
    mobile: "9876543217",
    marksScored: "87",
    appliedFor: "Class 8",
    seatsAvailable: "13",
  },
  {
    studentName: "Isla White",
    fatherName: "Thomas White",
    mobile: "9876543218",
    marksScored: "83",
    appliedFor: "Class 9",
    seatsAvailable: "10",
  },
  {
    studentName: "Jack Lee",
    fatherName: "Henry Lee",
    mobile: "9876543219",
    marksScored: "86",
    appliedFor: "Class 10",
    seatsAvailable: "12",
  },
  {
    studentName: "Kara Martin",
    fatherName: "Paul Martin",
    mobile: "9876543220",
    marksScored: "89",
    appliedFor: "Class 11",
    seatsAvailable: "11",
  },
  {
    studentName: "Liam Jackson",
    fatherName: "Mark Jackson",
    mobile: "9876543221",
    marksScored: "91",
    appliedFor: "Class 12",
    seatsAvailable: "10",
  },
];
export { classdata, rejectedStudentList, selectedStdList, totalStdList };
